### ISSUE TITLE
Option to clip and fit frame to parent div

### ISSUE THREAD

**Issue by hosnar** [OllieJones/Broadway#1]
Hello,

thank you for this fork, it already helped us a lot.

I have a question, would it be possible to not only scale frames/images but also clip them to the aspect ratio of parent div (so it takes the whole width and height, and overflowing parts are cut)? Some kind of clip and fit effect, that would clip the image in center to fit the parent div.

Thanks a lot!

**Comment by OllieJones** [comment]
Good question. Here's my attempt at an answer.   https://github.com/OllieJones/Broadway/blob/master/scaling.md
